### PR TITLE
Bump riscv-tests.

### PR DESCRIPTION
**Pull request by richardxia**
I'm bumping this mostly to pull in some changes to the ISA tests, but it looks like a lot of debug things were updated as well.

### CODE REVIEW

**Comment by aswaterman** [comment]
@richardxia @palmer-dabbelt Is it a good time to bump spike, pk, and gnu-toolchain as well?

**Comment by mwachs5** [comment]
@timsifive is this likely to pass without bumping riscv-openocd and riscv-isa-sim as well?

**Comment by timsifive** [comment]
I can't think of a failure off the top of my head, but OpenOCD hasn't been updated in a months IIRC, so I would be surprised if the tests pass without it.

**Comment by palmer-dabbelt** [comment]
It's a bad time to bump riscv-gnu-toolchain.

**Comment by richardxia** [comment]
@timsifive, it looks like Travis failed with an error in the debug tests. Can you bump OpenOCD and any other relevant submodules in this branch to whatever version will get the debug tests passing?

**Comment by timsifive** [comment]
Is there any reason not to bump OpenOCD to the latest? That's what I would
try first. Generally speaking I ensure that the latest version of all
components work together. If that doesn't pass, I'd also bump
to 58b6c187df1a5cc066c97a63483d297fd159f241 of riscv-isa-sim. gdb hasn't
changed in a long time, so shouldn't really matter.

**Comment by richardxia** [comment]
> Is there any reason not to bump OpenOCD to the latest?

No, as long as it's is safe to use. I don't know if in general the HEAD of the default branches of all these repos are safe to use.

I've preemptively bumped `riscv-isa-sim` to the latest `master` and `riscv-openocd` to the latest `riscv`. I am, however, marking this branch as `DO NOT MERGE` because I want to pull in one more change to `riscv-tests` before merging: https://github.com/riscv/riscv-tests/pull/88

**Comment by richardxia** [comment]
@timsifive, it looks like one of the debug tests (`MulticoreRegTest`) is still failing. See this [Travis build](https://travis-ci.org/riscv/riscv-tools/builds/295083586?utm_source=github_status&utm_medium=notification), which is from a commit where I had bumped `riscv-isa-sim` and `riscv-openocd` to their respective HEADs, but before I pulled in riscv/riscv-tests#88. Presumably my current build is also going to fail for the same reason even with riscv/riscv-tests#88 merged in.

Can you fix the issue with that debug test?

**Comment by timsifive** [comment]
Looks like you did bump about everything, and the test is still failing. I
checked out and built your branch, and it appears to be failing
intermittently. To make progress, I suggest you comment out the test in
gdbserver.py and merge that. I'll dig into the test, but I won't be able to
fix it today.

**Comment by richardxia** [comment]
Okay, one more try, after commenting out the flaky debug test.

**Pull request merged**
