### PR TITLE
Bump OpenOCD for SBA Option command

### PR DESCRIPTION
**Pull request by mwachs5**
Do I need to make any corresponding changes to `riscv-isa-sim` or `riscv-tests`, since OpenOCD hasn't been bumped in a while? Or to `GDB`?

### CODE REVIEW

**Comment by mwachs5** [comment]
What about this commit? It looks OpenOCD related... https://github.com/riscv/riscv-gnu-toolchain/commit/1b80cbe97d2c29212398d3b74ddc54718ad32e23

Just trying to get to a clean place where OpenOCD/GDB work nicely together.

**Comment by jim-wilson** [comment]
On Tue, Mar 27, 2018 at 11:14 AM, Megan Wachs <notifications@github.com>
wrote:

> What about this commit? It looks OpenOCD related...
> riscv/riscv-gnu-toolchain@1b80cbe
> <https://github.com/riscv/riscv-gnu-toolchain/commit/1b80cbe97d2c29212398d3b74ddc54718ad32e23>
>
This is only needed if you try to canadian cross build a native riscv64
compiler.  None of our build scripts do that.  I only noticed it by
accident when I was testing unused Makefile rules to see what they do.

Jim

**Comment by timsifive** [comment]
I always order my commits so that at any time the latest version of OpenOCD works with the latest version of GDB, works with riscv-tests. If that's not possible I'll commit them close together in time, but I don't remember having to do that in quite a while.

**Comment by jim-wilson** [comment]
On Tue, Mar 27, 2018 at 11:14 AM, Megan Wachs <notifications@github.com>
wrote:

> @mwachs5 <https://github.com/mwachs5> requested your review on:
> riscv/riscv-tools#185 <https://github.com/riscv/riscv-tools/pull/185>
> Bump OpenOCD for SBA Option command.
>

I don't know anything about OpenOCD.  You have to have access to hardware
to use it, and I don't have access to hardware.

Jim

**Pull request merged**
