### PR TITLE
Bump tests and spike

### PR DESCRIPTION
**Pull request by aswaterman**

### CODE REVIEW

**Comment by aswaterman** [comment]
@timsifive MulticoreRunHaltStepiTest still fails on spike64_2 after bumping riscv-openocd.  I'm kind of blocked on this, so is it best to temporarily disable that test in riscv-tests, or can you look into it soon?

**Comment by timsifive** [comment]
I won't have time to look at it today, so please disable it. Sorry for the mess.

**Comment by timsifive** [comment]
I've disabled the test in https://github.com/riscv/riscv-tests/commit/51ec34e28541f8c89cd89a6a9c137bd32ba71c29

**Comment by aswaterman** [comment]
No prob, thanks for taking the intermediate action.

**Pull request merged**
