### PR TITLE
Add a "--with-xlen=*" argument to build.sh

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
A few people have run into trouble building a consistent 32-bit
userspace.  With any luck, this will aid them.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
I hope this fixes https://github.com/riscv/riscv-tools/pull/39

**Comment by morse-michael** [comment]
Thanks for this fix @palmer-dabbelt!  The riscv32 gnu toolchain builds successfully for me now, but riscv-tests still fails on HoB with the the following error:

> Configuring project riscv-tests
> configure: WARNING: using cross tools not prefixed with host triplet
> Building project riscv-tests
> gmake[1]: riscv64-unknown-elf-gcc: Command not found

Seems to be because of the following Makefile variable in riscv-tests/benchmarks/Makefile:

`RISCV_PREFIX ?= riscv64-unknown-elf-
`

When I override RISCV_PREFIX in my build.sh with the following then I get past this issue but hit another error a bit further on when it tries to build some 64b stuff:

`export RISCV_PREFIX=$RISCV/bin/riscv"$with_xlen"-unknown-elf-
`

Error:

> /tools/riscv-tools/riscv-tools.20160901-master/riscv-tests/build/../isa/rv32si/shamt.S: Assembler messages:
> /tools/riscv-tools/riscv-tools.20160901-master/riscv-tests/build/../isa/rv32si/shamt.S:23: Warning: Improper shift amount (32)
> /tools/riscv-tools/riscv-tools.20160901-master/riscv-tests/build/../isa/rv64ui/addiw.S: Assembler messages:
> /tools/riscv-tools/riscv-tools.20160901-master/riscv-tests/build/../isa/rv64ui/addiw.S:20: Error: unrecognized opcode `addiw x3,x1,((0x000)|(-(((0x000)>>11)&1)<<11))'
> ...
> gmake[1]: *** [rv64ui-p-addiw] Error 1
> gmake: *** [isa] Error 2

Does " ./build.sh --with-xlen=32" work for you on a fresh checkout / am I missing something?

Thanks!

Michael

**Comment by susi655** [comment]
Hi morse-michael!
Hey same problem for me even. Riscv 32-bit toolchain installed properly. 
But did you try checking spike pk test?

I tried like following, with the hope that except riscv-tests everything is proper.
$riscv32-unknown-elf-gcc -o hello hello.c
$spike pk hello
terminate called after throwing an instance of 'std::runtime_error'
what(): could not open pk

But in installed file there is pk. There may be issue with locating pk. Can you try and inform me the status?

**Comment by morse-michael** [comment]
@susi655: you'll need to point spike to your 32b installation of pk, you'll also need to pass an isa string to spike specifying a 32b architecture as the default is RV64IMAFDC, see https://github.com/riscv/riscv-tools/issues/41.

**Comment by shrshore** [comment]
I tried 
```
./build.sh --with-xlen=32
```
But encountered many errors indicating format unmatched, and when i try this command and make,
```
~/riscv-tools/riscv-isa-sim$ ./configure --prefix=$RISCV --with-fesvr=$RISCV --with-xlen=32
```
The errors still remain. One of them is as follows.
```
./riscv/gdbserver.cc: In member function ‘void gdbserver_t::handle_packet(const std::vector<unsigned char>&)’:
./riscv/gdbserver.cc:1737:86: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘std::vector<unsigned char>::size_type {aka unsigned int}’ [-Werror=format=]
     fprintf(stderr, "Received %ld-byte packet with invalid checksum\n", packet.size());
                                                                                      ^
```
The version of my OS is
```
Linux ubuntu32 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:06:37 UTC 2016 i686 i686 i686 GNU/Linux
```
I'll appreciate it very much is someone can fix this problem....=.=

**Pull request merged**
