### PR TITLE
Bump riscv-tests to pull in changes related to OpenOCD GDB server port randomization.

### PR DESCRIPTION
**Pull request by richardxia**
@aswaterman, @timsifive

This bumps the version of `riscv-tests` to pull in https://github.com/riscv/riscv-tests/pull/35. However, it looks like the other recent changes to `riscv-tests` are causing the [Travis build to fail](https://travis-ci.org/riscv/riscv-tools/builds/175934277). I'm pretty sure that my change is unrelated because I only changed the behavior of our OpenOCD wrapper, which isn't called at all in the Travis tests.

The specific error is:

```
make -C debug -f /home/travis/build/riscv/riscv-tools/riscv-tests/build/../debug/Makefile src_dir=/home/travis/build/riscv/riscv-tools/riscv-tests/build/../debug XLEN=64
make[1]: Entering directory `/home/travis/build/riscv/riscv-tools/riscv-tests/build/debug'
/home/travis/build/riscv/riscv-tools/riscv-tests/build/../debug/gdbserver.py --isolate --spike64 --cmd spike \
	    > spike64.log 2>&1 || (sed s/^/spike64.log:\ / spike64.log && false)
spike64.log: Running DebugBreakpoint .../home/travis/riscv_install/lib/gcc/riscv64-unknown-elf/6.1.0/../../../../riscv64-unknown-elf/bin/ld: /tmp/ccL3WPtW.o: can't link hard-float modules with soft-float modules
spike64.log: /home/travis/riscv_install/lib/gcc/riscv64-unknown-elf/6.1.0/../../../../riscv64-unknown-elf/bin/ld: failed to merge target specific data of file /tmp/ccL3WPtW.o
spike64.log: collect2: error: ld returned 1 exit status
spike64.log:  exception while compiling in 0.07s
```

Can one or both of you help with getting the build passing?

### CODE REVIEW

**Comment by aswaterman** [comment]
I'm attempting a blind fix.  (Can't test it locally because I need sysadmin intervention to get some packages installed.)

**Comment by aswaterman** [comment]
Seems like that fixed the matter at hand, but now it's failing for unrelated reasons... @timsifive any insight into https://travis-ci.org/riscv/riscv-tools/builds/175970425?

**Comment by timsifive** [comment]
Yes. This build used 53d74f4cc31ecf5bb6499b886d8fcbc992a17920 of
riscv-isa-sim, but FPU debug support wasn't added
until ecff67fb34d50cc80822301f4de986be96da971c. You'll have to bump
riscv-isa-sim as well.

Tim

**Comment by richardxia** [comment]
Thanks, I'm bumping `riscv-isa-sim` now. Let's see if this passes Travis this time.

**Comment by richardxia** [comment]
Looks like it passed! Going to merge now. @aswaterman, can you also merge in your small fix to `riscv-tests`?

**Pull request merged**
