### PR TITLE
bump opcodes/spike/tests for satp/stval rename

### PR DESCRIPTION
**Pull request by aswaterman**

### CODE REVIEW

**Comment by mwachs5** [comment]
oops. I accidentally hit the "update branch" button. Apologies if that broke something for you @aswaterman

**Comment by aswaterman** [comment]
When it's time to merge, just use the squash & merge button to avoid the redundant merge commit

**Comment by mwachs5** [comment]
Is this covered by #158 ?

**Comment by aswaterman** [comment]
ah yes

**Pull request closed without merging**
