### PR TITLE
Add more dependencies for OS X

### PR DESCRIPTION
**Pull request by schoeberl**

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
Ugh, we're up against the Travis time limit again.  I restarted the build (maybe it's fast this time :)), but IIRC we had some ideas as to how to make this faster?  I don't remember what they were, though...

**Comment by colinschmidt** [comment]
I don't think it will make it faster but you can try using the stages feature that rocket-chip recently adopted. That way the limit is that each stage finish within the time limit rather than the whole build.

**Comment by arunthomas** [comment]
Does the time limit go away if we get a paid Travis account? Would a paid
Travis account be generally useful?

**Comment by aswaterman** [comment]
I'm going to email travis support and request an increase

**Comment by aswaterman** [comment]
They've kindly increased the build timeout to 90 mins.

**Comment by schoeberl** [comment]
Did the merge of this trivial change got lost due to the discussion on the build bot?

**Comment by palmer-dabbelt** [comment]
Yep.  Sorry about that.

**Pull request merged**
