### PR TITLE
Bump OpenOCD, GNU tools (incl. gdb), and tests

### PR DESCRIPTION
**Pull request by timsifive**

### CODE REVIEW

**Comment by mwachs5** [comment]
@timsifive it looks like this failed :(

```
b _exit
Breakpoint 1 at 0x1212340bf4: file ../../debug/programs/init.c, line 36.
(gdb) b main:start
b main:start
Breakpoint 2 at 0x12123405dc: file ../../debug/programs/debug.c, line 59.
(gdb) c
c
Continuing.
Breakpoint 2, main () at ../../debug/programs/debug.c:60
60	    while (i)
(gdb) p/x fib(6)
p/x fib(6)
Could not fetch register "ft0"; remote failure reply 'E0E'
(gdb) ^CQuit
(gdb) disassemble
disassemble
```

**Comment by timsifive** [comment]
Yeah. This is the same failure as before, but I thought I'd fixed it by properly bumping gdb this time.

I'll look at it next week.

**Comment by mwachs5** [comment]
Ready to merge?

**Comment by timsifive** [comment]
I'll take that as "approved."

**Pull request merged**
