### PR TITLE
unifying the build script and updating the README file

### PR DESCRIPTION
**Pull request by hall**
The README was confusing so I've tried to make it a bit more approachable; sorry that I did it all in about one commit! I also converted it to AsciiDoc because Markdown doesn't have all of the features that previous authors seemed to want (automatic table of contents, section links, admonition blocks, ...).

I've also combined all of the various build scripts into one. I haven't tested every case but it should work; run it with the `-h` flag to see how to use it.

### CODE REVIEW

**Comment by palmer-dabbelt** [comment]
Thanks.  Can you update .travis.yml as well so the tests run again?

**Comment by evancox10** [comment]
Just wanted to comment that this looks a lot easier to use, however can you add some directions on how to build specific versions of the toolset? For example default 32-bit ISA for the tools, or building riscv-pk to only use a subset of instructions (e.g. rv32im). This would be very helpful I think, a lot of questions pop up on how to get all of this working for embedded applications that aren't rv64g or rv32g.

**Comment by jcpunk** [comment]
Checking in on this, it looks like it would be awesome.

**Comment by palmer-dabbelt** [comment]
It looks like there's a bunch of conflicts here, but if someone wants to update it then I'm happy with improvements.

**Pull request closed without merging**
